### ISSUE TITLE
Import Error During llama stack configure <name>

### ISSUE THREAD

**Issue by cheesecake100201** [meta-llama/llama-stack#110]
```
 File "/usr/local/Caskroom/miniconda/base/envs/llama/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/together/__init__.py", line 7, in <module>
    from .config import TogetherImplConfig, TogetherHeaderExtractor
  File "/usr/local/Caskroom/miniconda/base/envs/llama/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/together/config.py", line 11, in <module>
    from llama_stack.distribution.request_headers import annotate_header
ImportError: cannot import name 'annotate_header' from 'llama_stack.distribution.request_headers' (/usr/local/Caskroom/miniconda/base/envs/llama/lib/python3.10/site-packages/llama_stack/distribution/request_headers.py)
```

This is the error I am getting while I run llama stack configure <name> using together inference API.

**Comment by CAholder** [comment]
This issue is fixed in the current main branch. The version on PIP does not reflect the fix just yet as they just updated it 3 days ago. 

You will need to go directly to this file on your installation and update it to the same one on main linked below. 

https://github.com/meta-llama/llama-stack/blob/eb2d8a31a5927589197c794855d7323f8f4700bc/llama_stack/providers/adapters/inference/together/config.py

**Comment by ashwinb** [comment]
Thanks for the comment @CAholder -- we will get our packages updated today. We have a few other small fixes.

**Comment by ashwinb** [comment]
0.0.37 has been out now. This should be fixed.
