### ISSUE TITLE
Is there a way to specify the download path?

### ISSUE THREAD

**Issue by SetoKaiba** [meta-llama/llama-stack#111]
For windows, it uses the default user profile path in C drive. But mostly, the C drive is not the large enough path for download large models. Is there a way to specify the download path? Thank you.

**Comment by bhargavyagnik** [comment]
You can change the root path at [Line 11](https://github.com/meta-llama/llama-stack/blob/2802ac8e9dff82aa35e65c89fbbb4973cddceb53/llama_stack/distribution/utils/config_dirs.py#L11C1-L11C63) 
`LLAMA_STACK_CONFIG_DIR = Path(os.path.expanduser("~/.llama/"))`

For reference the path is :
llama_stack/distribution/utils/config_dirs.py

After changing, you can build the repo or if you previously did `pip install -e .` then it should work.

**Comment by SetoKaiba** [comment]
Thank you. I thought that there's some kind of environment variable or arguments to specify without code modification.

**Comment by ralph-thompson** [comment]
Hi, I have set the variable LLAMA_STACK_CONFIG_DIR but this is still failing with python installed in C:, i think because of the way TEMPLATE_PATH in llama_stack\cli\stack\build.py is constructed:

TEMPLATES_PATH = Path(os.path.relpath(__file__)).parent.parent.parent / "templates"

It gives me this error:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python311\Scripts\llama.exe\__main__.py", line 4, in <module>
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_stack\cli\llama.py", line 11, in <module>
    from .stack import StackParser
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_stack\cli\stack\__init__.py", line 7, in <module>
    from .stack import StackParser  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_stack\cli\stack\stack.py", line 11, in <module>
    from .build import StackBuild
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_stack\cli\stack\build.py", line 22, in <module>
    TEMPLATES_PATH = Path(os.path.relpath(__file__)).parent.parent.parent / "templates"
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 758, in relpath
ValueError: path is on mount 'C:', start on mount 'D:'`

**Comment by ralph-thompson** [comment]
from docs for relpath:

> os.path.relpath(path, start=os.curdir)

> Return a relative filepath to path either from the current directory or from an optional start directory. This is a path computation: the filesystem is not accessed to confirm the existence or nature of path or start. On Windows, [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) is raised when path and start are on different drives.

**Comment by ralph-thompson** [comment]
For anyone having the same issue, as a workaround you can hardcode the TEMPLATE_PATH variable in llama_stack\cli\stack\build.py towards the \llama_stack\templates folder inside your python directory, for example:
TEMPLATES_PATH = Path("C:\\Users\ralph\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_stack\templates")

**Comment by ashwinb** [comment]
@ralph-thompson I am a little confused why this fails. If llama-stack is installed in C:\, why is a file from that drive unreadable? We don't have much experience working with Windows.

**Comment by ralph-thompson** [comment]
> @ralph-thompson I am a little confused why this fails. If llama-stack is installed in C:, why is a file from that drive unreadable? We don't have much experience working with Windows.

not an expert but I think maybe relpath is the culprit. The docs mention it can throw a value error in windows if the path and start are on different drives. I would guess the default start point must be the location you run from? and the path is where python is. So maybe the start parameter needs also to be also set as _file_ to avoid picking up the variable default value?

**Comment by ashwinb** [comment]
why do we need `relpath` there? We almost certainly don't and it is probably an oversight. cc @yanxi0830

**Comment by ashwinb** [comment]
@ralph-thompson https://github.com/meta-llama/llama-stack/commit/358db3c5b6b1de9243583af9c1efcc52285577a9 might fix this. It will go out in the next package update whenever that happens.
